### PR TITLE
apply %s, ratios, and density to textures in points

### LINKED ISSUE #638: support size: % and auto when no sprites set
Support percentage and ratio sizes, eg: `size: 50%` and `size: [16px, auto]` when no sprites set, to match ES implementation.
https://github.com/tangrams/tangram-es/blob/43efd63c69d1c018c80ee00bb8eab33f7788168b/core/src/style/pointStyleBuilder.cpp#L350

Sub-issues: #642, #644

Related:
- https://github.com/tangrams/tangram/issues/438
- https://github.com/tangrams/tangram/pull/234

### LINKED ISSUE #642: `auto` should apply if no sprites set
**TANGRAM VERSION:**

0.15.1

**ENVIRONMENT:**

macOS 10.13.4, Chrome 66 & Firefox

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
Using a 64px image, I used this scene file:
```yaml
sources:
    tilezen:
        type: TopoJSON
        url: https://tile.nextzen.org/tilezen/vector/v1/512/all/{z}/{x}/{y}.topojson
textures:
    icons:
        url: mapzen.png
layers:
    mypois:
        data: { source: tilezen, layer: pois }
        draw:
            points:
                texture: icons
                size: [16px, auto]
```
**RESULT:**

The points were drawn 64px x 64px.

**EXPECTED RESULT:**

Expected 16px x 16px. If I use a sprite, the ratio works:

```yaml
sources:
    tilezen:
        type: TopoJSON
        url: https://tile.nextzen.org/tilezen/vector/v1/512/all/{z}/{x}/{y}.topojson
textures:
    icons:
        url: images/mapzen.png
        sprites:
            thesprite: [0, 0, 64, 64]
layers:
    mypois:
        data: { source: tilezen, layer: pois }
        draw:
            points:
                texture: icons
                sprite: thesprite
                size: [16px, auto]
```

### LINKED ISSUE #644: % sizes should apply when no sprites set
Same as https://github.com/tangrams/tangram/issues/642 but for a `size` using a %:

```yaml
sources:
    tilezen:
        type: TopoJSON
        url: https://tile.nextzen.org/tilezen/vector/v1/512/all/{z}/{x}/{y}.topojson
textures:
    icons:
        url: mapzen.png
layers:
    mypois:
        data: { source: tilezen, layer: pois }
        draw:
            points:
                texture: icons
                size: 50%
```

### PR DESCRIPTION
**Pull request by meetar**
Currently, `points` styles which do not have sprites defined can only specify `size` in fixed values of `px`. Additionally, setting a `density` in the texture definition has no effect.

This PR will allow points styles to use percentages (`size: 50%`) and ratios (`size: [16px, auto]` or `size: [50%, auto]`), and will use `density` in css_size calculations.

Fixes #638, fixes #642, and fixes #644.

### CODE REVIEW

File: src/styles/points/points.js [hunk 1]
```diff
@@ -151,30 +151,42 @@ Object.assign(Points, {
...
+            style.size = StyleParser.evalCachedPointSizeProperty(draw.size, sprite_info, Texture.textures[style.texture], context);
             if (style.size == null) {
-                log({ level: 'warn', once: true }, `Layer '${draw.layers[draw.layers.length-1]}': ` +
-                    `'size' includes % and/or ratio-based scaling (${JSON.stringify(draw.size.value)}); ` +
-                    `these can only applied to sprites, but no sprite was specified, skipping features in layer`);
-                return;
+                // the StyleParser couldn't evaluate a sprite size -
+                // this means no sprite was defined, use the texture size
+                let tex = Texture.textures[style.texture];
+                let factor = (draw.size.value.indexOf('%') > -1 ? parseFloat(draw.size.value) : 1.0) / 100.0;
```
Comment (bcamper) [inline src/styles/points/points.js]: Wanted to note that the reason for all of the `evalCache...` functions is to avoid (wherever possible) re-evaluating this type of logic per-feature (e.g. if it's a static value like `size: 50%`, it can be evaluated and cached once per texture). While this particular usage (% sizing on texture, without a sprite) is probably not common, the caching can have a significant impact, and it would be better to add this logic to the underlying `StyleParser.evalCachedPointSizeProperty` function (looks like you're passing the full texture in anyway, so should have the context necessary).

Comment (meetar) [reply src/styles/points/points.js]: Ah, I see what happened here – https://github.com/tangrams/tangram/commit/523431ef0ca67a44f15986a4b966b00621d18c1f obviated https://github.com/tangrams/tangram/commit/e3f0d175784436b69c433c7f48106bc0a6e7b9a4 … I'll put a warning back in case something odd happens, but this texture size evaluation is no longer needed.
